# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-05 15:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0008_afs_imagevault_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="This is 'field' in the API", max_length=50)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='available_mimetypes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], help_text='Available mimetypes for this asset (not used)'),
        ),
        migrations.AddField(
            model_name='file',
            name='dc_title',
            field=models.CharField(blank=True, help_text='Most readable image title. Duplicated in self.name field at the moment', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='entity_uuid',
            field=models.UUIDField(default=None, help_text='Not used at the moment', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.UUIDField(default=None, help_text='Not used at the moment', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='media_id',
            field=models.UUIDField(default=None, help_text="Unique identifier for a medium, this is 'id' for the API", null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mediatype',
            field=models.CharField(blank=True, help_text="Only 'image' is used at the moment", max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='mimetype',
            field=models.CharField(blank=True, help_text="One of the available_mimetypes, most probably 'image/tiff'", max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='The order of this asset in the media'),
        ),
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=None, help_text='Unique identifier for an asset. Base of the file name in the API', null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.MetadataField'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
        migrations.AddField(
            model_name='file',
            name='metadata_fields',
            field=models.ManyToManyField(through='filer.Metadata', to='filer.MetadataField'),
        ),
    ]
