# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('filer', '0011_auto_20180117_1742'),
    ]

    operations = [
    ]
