# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import filer.fields.multistorage_file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_merge_20180502_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=filer.fields.multistorage_file.MultiStorageFileField(blank=True, max_length=500, null=True, upload_to=filer.fields.multistorage_file.generate_filename_multistorage, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='original filename'),
        ),
    ]
